management:
  server:
    port: 8081
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /wisehero # http://localhost:8081/wisehero/actuator? ??????.

logging:
  level:
    hello.controller: DEBUG
